# Generated by Django 4.1 on 2022-08-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('roll_number', models.IntegerField()),
                ('mobile', models.CharField(max_length=20)),
            ],
        ),
    ]
